# Boolean
navigation: true
welcome: false
# Site Settings
title: MyERPPlus
email: Nonita@gmail.com
version: v1.0.2
log_date: 2017-09-08 23:56:01
author: Nonita
description: >
  Ini adalah Blog Betta Dev Indonesia Education
baseurl: "" # Sesuaikan dengan root / nama folder
url: "http://127.0.0.1:4000" # Sesuaikan dengan nama url website
twitter_username: yourtwitter
github_username:  yourgithub

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM